import type { Evidence } from "@/types/evidence";

export const evidence: Evidence[] = [
  {
    id: "e1",
    title: "깨진 머그컵",
    category: "OBJECT",
    summary: "피해자 책상 오른쪽 아래에서 발견된 깨진 머그컵.",
    detail:
      "컵은 손잡이 부분이 부러진 채 책상 아래에 떨어져 있었다. 파편은 책상 다리 근처에 모여 있었지만, 주변 바닥에는 음료가 넓게 번진 흔적이 거의 없다. 컵 안쪽에는 말라붙은 갈색 자국이 남아 있다.",
    location: "피해자 책상",
    unlockOrder: 0,
    importance: "IMPORTANT",
    observation: "컵이 깨진 방식과 주변 흔적이 자연스럽지 않다.",
    notebookEntry: "깨진 머그컵 발견. 컵은 깨져 있지만 주변에 액체가 크게 흘러 있지 않다.",
    unlockedQuestion: "왜 컵은 깨졌는데 액체 흔적은 거의 없을까?",
    relatedEvidenceIds: ["e5"],
    relatedTimelineTimes: ["23:50"],
  },
  {
    id: "e2",
    title: "꺼진 CCTV 기록",
    category: "CCTV",
    summary: "사건 직전 30분간 12층 전체 CCTV가 정전으로 꺼져 있었다.",
    detail: "정전은 12층에만 국한되었고, 배전반에 수동 조작 흔적이 남아 있다.",
    location: "관제실 서버",
    unlockOrder: 0,
    importance: "IMPORTANT",
    relatedEvidenceIds: ["e6"],
    relatedSuspectIds: ["s1"],
    relatedTimelineTimes: ["20:05", "20:30"],
  },
  {
    id: "e3",
    title: "피해자의 노트북",
    category: "DOCUMENT",
    summary: "피해자 책상 위에 열려 있던 업무용 노트북.",
    detail:
      "노트북은 절전 상태였고, 화면을 켜자 마지막으로 열려 있던 문서 목록이 남아 있었다. 최근 파일명에는 ‘조직개편_최종검토’, ‘예산조정안’, ‘면담기록’이 포함되어 있다. 단, 일부 문서는 비밀번호가 필요하다.",
    location: "피해자 책상",
    unlockOrder: 1,
    unlockCondition: { requiresEvidenceIds: ["e1", "e2"] },
    importance: "IMPORTANT",
    observation: "피해자는 사건 직전까지 업무 문서를 검토하고 있었던 것으로 보인다.",
    notebookEntry:
      "피해자의 노트북 확인. 조직개편, 예산조정, 면담기록 관련 문서가 최근 열람되어 있었다.",
    unlockedQuestion: "피해자는 사건 직전 누구와 무엇을 검토하고 있었을까?",
    relatedSuspectIds: ["s1"],
  },
  {
    id: "e4",
    title: "잠긴 출입문",
    category: "OBJECT",
    summary: "사건 당시 닫혀 있던 기획전략실 출입문.",
    detail:
      "출입문은 자동 잠금 장치가 걸린 상태였다. 외부 파손 흔적은 없고, 문손잡이 주변에도 강제로 열린 흔적은 보이지 않는다. 다만 출입 기록 확인 없이는 누가 마지막으로 드나들었는지 단정할 수 없다.",
    location: "출입문",
    unlockOrder: 1,
    importance: "IMPORTANT",
    observation: "문은 잠겨 있었지만, 그것만으로 외부 침입이 없었다고 판단할 수는 없다.",
    notebookEntry: "출입문 확인. 강제 침입 흔적은 없으나 출입 기록 확인이 필요하다.",
    unlockedQuestion: "문은 정말 안에서 잠긴 것이 맞을까?",
    relatedSuspectIds: ["s1"],
  },
  {
    id: "e5",
    title: "책상 아래 혈흔",
    category: "FORENSIC",
    summary: "회의실 바닥과 책상 아래쪽에서 확인된 작은 혈흔.",
    detail:
      "혈흔은 넓게 번져 있지 않고, 책상 아래 안쪽에 작게 남아 있었다. 주변에는 끌린 자국이나 격렬한 몸싸움의 흔적이 뚜렷하지 않다. 혈흔의 양은 최초 신고 내용과 비교하면 많지 않은 편이다.",
    location: "회의실 바닥",
    unlockOrder: 2,
    unlockCondition: { requiresEvidenceIds: ["e3"] },
    importance: "CRITICAL",
    observation: "현장에서 보이는 상황과 혈흔의 양이 직관적으로 맞지 않는다.",
    notebookEntry: "책상 아래 혈흔 확인. 혈흔은 존재하지만 양이 많지 않고, 주변 흔적도 제한적이다.",
    unlockedQuestion: "피해자는 정말 이 자리에서 치명상을 입은 것일까?",
    relatedEvidenceIds: ["e1"],
    relatedSuspectIds: ["s1"],
  },
  {
    id: "e6",
    title: "정전 기록",
    category: "DOCUMENT",
    summary: "12층 배전반에 수동 조작 흔적.",
    detail: "정전 시각 직전 배전반 앞에 접근한 인물은 박민수. 출입 카드 로그로 확인됨.",
    location: "12층 배전반",
    unlockOrder: 2,
    unlockCondition: { requiresEvidenceIds: ["e2"] },
    importance: "CRITICAL",
    relatedEvidenceIds: ["e2"],
    relatedSuspectIds: ["s1"],
    relatedTimelineTimes: ["20:05"],
  },
];
