import type { Evidence } from "@/types/evidence";

export const evidence: Evidence[] = [
  {
    id: "e1",
    title: "깨진 머그컵",
    category: "OBJECT",
    summary: "피해자 책상 옆에서 산산조각 난 채 발견.",
    detail: "커피 자국이 벽까지 튀어 있다. 다툼이 있었음을 시사한다.",
    location: "피해자 책상 옆",
    unlockOrder: 0,
    importance: "COMMON",
    relatedEvidenceIds: ["e5"],
    relatedTimelineTimes: ["23:50"],
  },
  {
    id: "e2",
    title: "꺼진 CCTV 기록",
    category: "CCTV",
    summary: "사건 직전 30분간 12층 전체 CCTV가 정전으로 꺼져 있었다.",
    detail: "정전은 12층에만 국한되었고, 배전반에 수동 조작 흔적이 남아 있다.",
    location: "관제실 서버",
    unlockOrder: 0,
    importance: "IMPORTANT",
    relatedEvidenceIds: ["e6"],
    relatedSuspectIds: ["s1"],
    relatedTimelineTimes: ["20:05", "20:30"],
  },
  {
    id: "e3",
    title: "피해자의 노트북",
    category: "PHONE",
    summary: "화면은 열린 채였고, 사건 직전 메시지가 일부 삭제된 흔적이 있다.",
    detail: "복구된 로그에서 '박' 으로 시작하는 이름과의 대화 일부가 확인된다.",
    location: "피해자 책상",
    unlockOrder: 1,
    unlockCondition: { requiresEvidenceIds: ["e1", "e2"] },
    importance: "UNCOMMON",
    relatedSuspectIds: ["s1"],
  },
  {
    id: "e4",
    title: "잠긴 사무실 문",
    category: "OBJECT",
    summary: "사무실 문은 안쪽에서 잠겨 있었다.",
    detail: "예비 열쇠 소지자는 팀장, 부팀장, 총무팀 3명뿐이다.",
    location: "사무실 출입문",
    unlockOrder: 1,
    importance: "UNCOMMON",
    relatedSuspectIds: ["s1"],
  },
  {
    id: "e5",
    title: "책상 아래 혈흔",
    category: "FORENSIC",
    summary: "책상 아래에서 소량의 혈흔 발견.",
    detail:
      "감식 결과 피해자의 것이 아닌 제3자의 혈흔. 부팀장 박민수의 손등 상처와 일치한다.",
    location: "책상 아래",
    unlockOrder: 2,
    unlockCondition: { requiresEvidenceIds: ["e3"] },
    importance: "CRITICAL",
    relatedEvidenceIds: ["e1"],
    relatedSuspectIds: ["s1"],
  },
  {
    id: "e6",
    title: "정전 기록",
    category: "DOCUMENT",
    summary: "12층 배전반에 수동 조작 흔적.",
    detail: "정전 시각 직전 배전반 앞에 접근한 인물은 박민수. 출입 카드 로그로 확인됨.",
    location: "12층 배전반",
    unlockOrder: 2,
    unlockCondition: { requiresEvidenceIds: ["e2"] },
    importance: "CRITICAL",
    relatedEvidenceIds: ["e2"],
    relatedSuspectIds: ["s1"],
    relatedTimelineTimes: ["20:05"],
  },
];
