/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseCaseIdRouteImport } from './routes/case.$caseId'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as CaseCaseIdIndexRouteImport } from './routes/case.$caseId.index'
import { Route as CaseCaseIdInvestigateRouteImport } from './routes/case.$caseId.investigate'
import { Route as CaseCaseIdAccuseRouteImport } from './routes/case.$caseId.accuse'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCaseIdRoute = CaseCaseIdRouteImport.update({
  id: '/case/$caseId',
  path: '/case/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const CaseCaseIdIndexRoute = CaseCaseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseCaseIdRoute,
} as any)
const CaseCaseIdInvestigateRoute = CaseCaseIdInvestigateRouteImport.update({
  id: '/investigate',
  path: '/investigate',
  getParentRoute: () => CaseCaseIdRoute,
} as any)
const CaseCaseIdAccuseRoute = CaseCaseIdAccuseRouteImport.update({
  id: '/accuse',
  path: '/accuse',
  getParentRoute: () => CaseCaseIdRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/case/$caseId': typeof CaseCaseIdRouteWithChildren
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/case/$caseId/accuse': typeof CaseCaseIdAccuseRoute
  '/case/$caseId/investigate': typeof CaseCaseIdInvestigateRoute
  '/case/$caseId/': typeof CaseCaseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/case/$caseId/accuse': typeof CaseCaseIdAccuseRoute
  '/case/$caseId/investigate': typeof CaseCaseIdInvestigateRoute
  '/case/$caseId': typeof CaseCaseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/case/$caseId': typeof CaseCaseIdRouteWithChildren
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/case/$caseId/accuse': typeof CaseCaseIdAccuseRoute
  '/case/$caseId/investigate': typeof CaseCaseIdInvestigateRoute
  '/case/$caseId/': typeof CaseCaseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/case/$caseId'
    | '/.mcp/invoke-tool/$tool'
    | '/case/$caseId/accuse'
    | '/case/$caseId/investigate'
    | '/case/$caseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
    | '/case/$caseId/accuse'
    | '/case/$caseId/investigate'
    | '/case/$caseId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/case/$caseId'
    | '/.mcp/invoke-tool/$tool'
    | '/case/$caseId/accuse'
    | '/case/$caseId/investigate'
    | '/case/$caseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CaseCaseIdRoute: typeof CaseCaseIdRouteWithChildren
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseId': {
      id: '/case/$caseId'
      path: '/case/$caseId'
      fullPath: '/case/$caseId'
      preLoaderRoute: typeof CaseCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseId/': {
      id: '/case/$caseId/'
      path: '/'
      fullPath: '/case/$caseId/'
      preLoaderRoute: typeof CaseCaseIdIndexRouteImport
      parentRoute: typeof CaseCaseIdRoute
    }
    '/case/$caseId/investigate': {
      id: '/case/$caseId/investigate'
      path: '/investigate'
      fullPath: '/case/$caseId/investigate'
      preLoaderRoute: typeof CaseCaseIdInvestigateRouteImport
      parentRoute: typeof CaseCaseIdRoute
    }
    '/case/$caseId/accuse': {
      id: '/case/$caseId/accuse'
      path: '/accuse'
      fullPath: '/case/$caseId/accuse'
      preLoaderRoute: typeof CaseCaseIdAccuseRouteImport
      parentRoute: typeof CaseCaseIdRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CaseCaseIdRouteChildren {
  CaseCaseIdAccuseRoute: typeof CaseCaseIdAccuseRoute
  CaseCaseIdInvestigateRoute: typeof CaseCaseIdInvestigateRoute
  CaseCaseIdIndexRoute: typeof CaseCaseIdIndexRoute
}

const CaseCaseIdRouteChildren: CaseCaseIdRouteChildren = {
  CaseCaseIdAccuseRoute: CaseCaseIdAccuseRoute,
  CaseCaseIdInvestigateRoute: CaseCaseIdInvestigateRoute,
  CaseCaseIdIndexRoute: CaseCaseIdIndexRoute,
}

const CaseCaseIdRouteWithChildren = CaseCaseIdRoute._addFileChildren(
  CaseCaseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CaseCaseIdRoute: CaseCaseIdRouteWithChildren,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
