/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseCaseIdRouteImport } from './routes/case.$caseId'
import { Route as CaseCaseIdInvestigateRouteImport } from './routes/case.$caseId.investigate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCaseIdRoute = CaseCaseIdRouteImport.update({
  id: '/case/$caseId',
  path: '/case/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCaseIdInvestigateRoute = CaseCaseIdInvestigateRouteImport.update({
  id: '/investigate',
  path: '/investigate',
  getParentRoute: () => CaseCaseIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case/$caseId': typeof CaseCaseIdRouteWithChildren
  '/case/$caseId/investigate': typeof CaseCaseIdInvestigateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case/$caseId': typeof CaseCaseIdRouteWithChildren
  '/case/$caseId/investigate': typeof CaseCaseIdInvestigateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case/$caseId': typeof CaseCaseIdRouteWithChildren
  '/case/$caseId/investigate': typeof CaseCaseIdInvestigateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/case/$caseId' | '/case/$caseId/investigate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/case/$caseId' | '/case/$caseId/investigate'
  id: '__root__' | '/' | '/case/$caseId' | '/case/$caseId/investigate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseCaseIdRoute: typeof CaseCaseIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseId': {
      id: '/case/$caseId'
      path: '/case/$caseId'
      fullPath: '/case/$caseId'
      preLoaderRoute: typeof CaseCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseId/investigate': {
      id: '/case/$caseId/investigate'
      path: '/investigate'
      fullPath: '/case/$caseId/investigate'
      preLoaderRoute: typeof CaseCaseIdInvestigateRouteImport
      parentRoute: typeof CaseCaseIdRoute
    }
  }
}

interface CaseCaseIdRouteChildren {
  CaseCaseIdInvestigateRoute: typeof CaseCaseIdInvestigateRoute
}

const CaseCaseIdRouteChildren: CaseCaseIdRouteChildren = {
  CaseCaseIdInvestigateRoute: CaseCaseIdInvestigateRoute,
}

const CaseCaseIdRouteWithChildren = CaseCaseIdRoute._addFileChildren(
  CaseCaseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseCaseIdRoute: CaseCaseIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
