/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseCaseIdRouteImport } from './routes/case.$caseId'
import { Route as CaseCaseIdIndexRouteImport } from './routes/case.$caseId.index'
import { Route as CaseCaseIdInvestigateRouteImport } from './routes/case.$caseId.investigate'
import { Route as CaseCaseIdAccuseRouteImport } from './routes/case.$caseId.accuse'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCaseIdRoute = CaseCaseIdRouteImport.update({
  id: '/case/$caseId',
  path: '/case/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCaseIdIndexRoute = CaseCaseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseCaseIdRoute,
} as any)
const CaseCaseIdInvestigateRoute = CaseCaseIdInvestigateRouteImport.update({
  id: '/investigate',
  path: '/investigate',
  getParentRoute: () => CaseCaseIdRoute,
} as any)
const CaseCaseIdAccuseRoute = CaseCaseIdAccuseRouteImport.update({
  id: '/accuse',
  path: '/accuse',
  getParentRoute: () => CaseCaseIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/case/$caseId': typeof CaseCaseIdRouteWithChildren
  '/case/$caseId/accuse': typeof CaseCaseIdAccuseRoute
  '/case/$caseId/investigate': typeof CaseCaseIdInvestigateRoute
  '/case/$caseId/': typeof CaseCaseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/case/$caseId/accuse': typeof CaseCaseIdAccuseRoute
  '/case/$caseId/investigate': typeof CaseCaseIdInvestigateRoute
  '/case/$caseId': typeof CaseCaseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/case/$caseId': typeof CaseCaseIdRouteWithChildren
  '/case/$caseId/accuse': typeof CaseCaseIdAccuseRoute
  '/case/$caseId/investigate': typeof CaseCaseIdInvestigateRoute
  '/case/$caseId/': typeof CaseCaseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/case/$caseId'
    | '/case/$caseId/accuse'
    | '/case/$caseId/investigate'
    | '/case/$caseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/case/$caseId/accuse'
    | '/case/$caseId/investigate'
    | '/case/$caseId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/case/$caseId'
    | '/case/$caseId/accuse'
    | '/case/$caseId/investigate'
    | '/case/$caseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  CaseCaseIdRoute: typeof CaseCaseIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseId': {
      id: '/case/$caseId'
      path: '/case/$caseId'
      fullPath: '/case/$caseId'
      preLoaderRoute: typeof CaseCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseId/': {
      id: '/case/$caseId/'
      path: '/'
      fullPath: '/case/$caseId/'
      preLoaderRoute: typeof CaseCaseIdIndexRouteImport
      parentRoute: typeof CaseCaseIdRoute
    }
    '/case/$caseId/investigate': {
      id: '/case/$caseId/investigate'
      path: '/investigate'
      fullPath: '/case/$caseId/investigate'
      preLoaderRoute: typeof CaseCaseIdInvestigateRouteImport
      parentRoute: typeof CaseCaseIdRoute
    }
    '/case/$caseId/accuse': {
      id: '/case/$caseId/accuse'
      path: '/accuse'
      fullPath: '/case/$caseId/accuse'
      preLoaderRoute: typeof CaseCaseIdAccuseRouteImport
      parentRoute: typeof CaseCaseIdRoute
    }
  }
}

interface CaseCaseIdRouteChildren {
  CaseCaseIdAccuseRoute: typeof CaseCaseIdAccuseRoute
  CaseCaseIdInvestigateRoute: typeof CaseCaseIdInvestigateRoute
  CaseCaseIdIndexRoute: typeof CaseCaseIdIndexRoute
}

const CaseCaseIdRouteChildren: CaseCaseIdRouteChildren = {
  CaseCaseIdAccuseRoute: CaseCaseIdAccuseRoute,
  CaseCaseIdInvestigateRoute: CaseCaseIdInvestigateRoute,
  CaseCaseIdIndexRoute: CaseCaseIdIndexRoute,
}

const CaseCaseIdRouteWithChildren = CaseCaseIdRoute._addFileChildren(
  CaseCaseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  CaseCaseIdRoute: CaseCaseIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
